spec:
  source:
    repoURL: https://argoproj.github.io/argo-helm
    chart: argo-cd
    targetRevision: 7.x.x
    helm:
      releaseName: argocd
      valuesObject:
        server:
          extraArgs: ["--insecure"]
          service: { type: ClusterIP }
          ingress:
            enabled: true
            ingressClassName: traefik
            annotations:
              traefik.ingress.kubernetes.io/router.entrypoints: web
            hosts:
              - argocd.local.lan
            paths:
              - /
            pathType: Prefix
        configs:
          secret: { createSecret: true }
