apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: argocd
  namespace: argocd
spec:
  suspend: true
  interval: 15m
  chart:
    spec:
      chart: argo-cd
      version: 7.x.x
      sourceRef:
        kind: HelmRepository
        name: argo
        namespace: flux-system
  values:
    server:
      extraArgs:
        - --insecure
      service:
        type: ClusterIP
