apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd   # ← CR itself goes here
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd   # ← chart installs into here
  source:
    repoURL: https://argoproj.github.io/argo-helm
    chart: argo-cd
    targetRevision: 7.x.x
    helm:
      releaseName: argocd
      valuesObject:
        server:
          extraArgs:
            - --insecure
          service:
            type: ClusterIP
          ingress:
            enabled: true
            ingressClassName: traefik
            annotations:
              traefik.ingress.kubernetes.io/router.entrypoints: web
            hostname: argocd.local.lan
            path: /
            pathType: Prefix
        configs:
          secret:
            createSecret: true
