apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: authentik
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.goauthentik.io
    chart: authentik
    targetRevision: 2024.12.3
    helm:
      values: |
        authentik:
          secret_key: "changeme"
          error_reporting:
            enabled: false
          postgresql:
            password: "changeme"

        global:
          envFrom:
            - secretRef:
                name: authentik-secrets

        postgresql:
          enabled: true
          image:
            registry: ghcr.io
            tag: "15"
          auth:
            username: authentik
            database: authentik
            existingSecret: authentik-secrets
            secretKeys:
              adminPasswordKey: AUTHENTIK_POSTGRESQL__POSTGRES_PASSWORD
              userPasswordKey: AUTHENTIK_POSTGRESQL__PASSWORD

        redis:
          enabled: true
          image:
            registry: ghcr.io
            tag: "7"

        server:
          ingress:
            enabled: true
            ingressClassName: traefik
            annotations:
              traefik.ingress.kubernetes.io/router.entrypoints: websecure
              traefik.ingress.kubernetes.io/router.tls: "true"
            hosts:
              - auth.local.lan
  destination:
    server: https://kubernetes.default.svc
    namespace: authentik
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
