---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgCEvdmqJbVr98KnKNuurgf6Bj6v9qrVNTHbGjxQ6sCppPuDDr5pgen553VIqFWeqC8G/i8QiljjXQ5k+Vk7k6Yz1juxB9HmMmPP4yVO0zpw9L3tO+aOZHjqaD22EDiUkJ90XuCPeuwR4Q0pnEcXdAufNtwi9HbGJUNF6c75bPfdxmcK9l8h313ETtvw4jkEXcwTR6XMrch1ZyI6P3D3HSJzck6pf/J4AuKyyzFTeHyJMkhNbogebCe2kEcKzaD31MoG2LcAhOSX0YGVjgxSydhaLggWP6rbktX7OawSydEwNGNDWMF7fQlRigrYNe6c/Jin3rgI5ZtQZ1tbaRq6Rqq7cTQMPaa7TtG8IXAkaOdDp+gA5hOfCLagFyf4czcBmYxDy1KKI6c+njGebX077JiVjZeygJsxX7hg7EAsO3RWure3lc2zVcQ5F4gEkgIZgPAMSdG66sa3EhCQZm4U/77GLbKSrVpjs9CdgwhKorWAl8kK+czWsB8/na3TtkmgoPCCBh7c2ImwsQiVC6cxUAR5LayR7Go4oLRXcLY+iHUWVfglo0xwxeySRxwpXtuEoI0bOsmuVGDHS3Nfl0SM0zoSSQ9uidha33WumJbTYdWLFrp+vUm/xgMK2WYn7SFQvR2ntskVw6Yi1js7bjQO0rBd++wYU5lGuOYRMBvBqjhN0+rTt6qhgc6Ey5rGjdO7ESsXCJF5mD/lqA8tuU2QKXvYtH2v7f2HAlRgYxGV1e6AKDyofMRs+saPgCnHCYKznuyTYjcYQg==
  template:
    metadata:
      name: cloudflare-api-token
      namespace: cert-manager
    type: Opaque
