---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgBYDP08orJ5sb2oafZxTseWsBcJopStAhh8tsKZNepn8LxhmGs11kUvOXLWWdIpyOEs66IemYBOnalpg9QaYJNYO6owOO52ctpZXeUpkjLO0jIKz3iHOmjduzyFEzhgUfV9SnlC3I+BG5PtZByCtshbWo1wIP/IL1Y+pAe2BEcT24AUNOU/Ht93ZNHdSFxTrqmnzfR1YK4141HLgVsdheVxS4SLQEEpdTOkk2l+TZWUvWU7GQ/QOfS74IX1esZLMFnT11euFIgBFSAVXaXxZnkV9dXKeQ8woLyL0GvW+RPuAdWL6U7OjYW4pCjcJJUIqnoBX6RTA6nomwZu/fWrbDokBUmcDSZrz4WeZK3UDMqQhAdvSIKzzjZ51gHFHIl9zDdrOeS+VD4+SWrdqVyxIVH5YTd7HQ9z0kUVeSekwLGoCTjJyoeZQr/zmv/kyPVw76M6/2uqch/zbMNQkQCVLXTGnVSbu0HchipiCXpsu+tBAS2BYWq0bKpx569GnYrN8aSRmZ/krxf+Z5S8V9yDsX+dLCh9KJ5wid9hZ8cMRIdEq3Z+GWT/g+gH6WIS3DEZ784aBdN+xV9IDSPB6DA6K02NEOXA76Fr497Qm2p44CZl6kj+pxJISf/+XZmhNqLNVTmdywJ9rNubgepNULYQI+3Z/Dm7aLeQn3aMrU1k1JUAB2bP02Vu3IEpjaZDUpyNsC+InMqlV/NlmuvQmlyaf4n/iG3EXDmx0JL7BVMQ1s4z3Ilayy6JLw/hNmOdguWzDvI/Fk9y7g==
  template:
    metadata:
      name: cloudflare-api-token
      namespace: cert-manager
    type: Opaque
