---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflared-token
  namespace: cloudflared
spec:
  encryptedData:
    token: AgCJp1OEqoi+WvKcvHoDgITjSlJpGB/3ZDS8vAu43+MIWt3DpR/Y1wTB6wbHtgnsT6QSjXp+xpSNaXjz/1rTytl2+TwtscjkPuBpY84+9Q0i9HCDJb/0brFs9rkOaJljCddJ8iKDblGVV8j0BiHpenawn8Xjb+/LCGsrc/2k2L5x3d54fu1IVvXFR5nx5MxbVJh3A/jDL868UF4UFVpvgQqtZj8culXEObIF4858c/kV3V9PmSXeL6yRDaFqCOh1E0Nb0+kdeo4cP+O53Mt0aFl8CS+ehcprCS9C+u08ORN7sVYXpzJ6tyh+CduUyjkiZxcdwlfxFLO7H8uuO5qDYYt9GJAopGqjFuBEEG67DpZoWIEl9rny2aVhi5Y93tq35tbduiwI/dq9l8GH6tK/ijVRuCogqvu3e9jpt7vehK4rX76jWf0/vzmG2MGavTUGZ5MdlK1qmp5Ajma4kif8sgCIBeU4/tQlhIv5h6LtGQfBaieb1Z6Wd6Adqj0ZktKo3pCzNHYcdAwCItwDlgTJobIDqh4Ac6cYDTutsVo8sgjj2wU1rkr2IV0JHQMJTFa6bLxoYznq6o3Jtlbv/xeO0RDWJ3FbNSnk9fuDYQ0Y+PcdA9MV7ELoO5nwQwhAIyhwL0rieeRc+3AUp1gperxududEA0lgvE1BJTn1uwtDg77OIPY/MFCWMXXe1+b3VW1Ua74o3wx32WDfQVYflLuuSxnIlE7Thrk5tVmg5CGIQkT9efya0glCy/jKDzlPNsB5uYzHYVy9soNtr2UoODD7F3OsN5chOhga+J3yP74Sr6RsHTBSYcnpuXFA4525k3b5Dxx//fCi2hH/XRn09GjX0V3RWbm0PCl18Ar0Y/WcwrNq1LMfNYI4VOovx6QGGYVYuS51osQ603ZYTKbng0yJaaHgwKBAKlrcoRTwEV/IXh0ud6rVu2eaAbbh
  template:
    metadata:
      name: cloudflared-token
      namespace: cloudflared
    type: Opaque
