---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgBaQsyep4ifNgrLvRucCdngcNy+WWIJzdsvbxXTtzOxA6FHHFXKRX44j4VPbBh2yvkmKjClAlas+fo0YD4svU74wvIBeYTFxqingO7ul5WvkxBgJfpmVWvCOWXs/HRXieTkvq9aBZ1ykZ9qqzGUrFS7RWomUPfqTJFI7I2PfdJRSSqQpOnhLjXzp4qBTeFUeqRy+eB75WSkIckavknduAqlxdVma25+UxEucjU0ortk42QdBrmQvU3TZz2tbOuuGp3lGz8C/pUPiFFf9aTjY1sX5mMaaNkF6cr1YfMzDtfvr/Uvd5EDrGoVQ6a5Vj9GV85inLUnKo/CNqfQdhp/zrOdCR4lvfUt5Bq1PUVBrAuHvypHlgpumwyp4ln9gceHc+qeLLu1ii/DFj8DQ0He9yEISDYodIRx30aqaIgBePmECKkNiA/WtDLdGVQ0Y5OS/VoVBuAcw3R9HWmeakVPmpJOIjog0FdjBBBBpswc5JRNy29ziE1gWjzpNjrDcipURxANB/MeVqFNKGoeWsc7O0wOyl3rMr+yki7NP7VPSdz3j3TMhB6/DI8Gf0JVCPE3YonO6haZD/58dmWXRC3hhlKDVNkpoQey/DdoOncSDXW3rz/BJuK7kG2ZJdwwN4OmWrMFrray1ESj/tSD9r5cVn/+JFlJEbRUrZ3mBN/2mVhOKn2Y7fQa7DpPYjsB1owUecs3bvMGpQ0F2urHP+xEqm5McJZ3KFkRPufXRU1uxYGARIS78UfjCBU9LSo05gLYp1Lj3uO3Vg==
  template:
    metadata:
      name: cloudflare-api-token
      namespace: cert-manager
    type: Opaque
