---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflared-token
  namespace: cloudflared
spec:
  encryptedData:
    token: AgCL6O/NcD75xc+Ok4H8ZqFiuBS2hpOXmPuYuRPfeX0JrsHDb3ZvmE2CI3yCPDsFxHzjtRG3dXnn7FVYlUeced3THak5h1vXTCKfvjYuZCLTRdl+Joy6Hrd8IPiEVxYEu66tJ6YdE4socpjC28ZW+9JAUSBgaCSjiklXC6NbGZEPMPaxpsyin+gN4Y0p3+qcMsLzzYafx438yAqx1dTVd7wlRvpbNXov6BxZkqUqGP652jCAzzLq8XcUxQZWJxJren8SjJyYqyaGoI7VeoKdtAerdD1O5hP9a9zJtId+L4BMIJwJfxPUfey0xlHNvTW6TQaenWK241Oa/UL2Gt/XFYErcTml6lhrxUuS6Q1rcFTtQ8Ki7MCv4FSWCOoOCFuR9RCJ+uKe6Yp24XE5fI/z+ZBnc7quPwpFsri3SnQhqwlSwBLd6vcfQn2h05VD8X6JIXtq8aeCxqX+qAiEMmnpNGhIbktKyNh9VCN/fgpktvnupwiZNfVqENCsMGFJEPGQvA9AOJSW2UvxfdrVu1sbKOmns5IOsyrbceXlQjFNqMXZHLhPe9gaqM3Mj7V75bcb8CvUblPole7eeYxeeTZujsMRRYZqq2UbbaWmc18YplGFY38fup5C/g0cehvesiI4ldOiACsr+IamuX2DpY6TnQrS/FhqLtPL4V+OZ6wztNUTEiHc0p1f9OQjWDAlcf2W50NhhyZffT/F2xsg/qrlK2PbUlXx14m7dUIIwtnFAou+Z0o9gioEbiYBBM21lrnwYVgTqxO1mX9NCD3Xn9O6FL1KHYMWQNhydPzE3k4a+XNXiHud7Tnb2fLEYJZX4s74xI4JYBnOvOxUeHJQUNAbVtegMMVE57i8XnhxnZJdfIiYYYeJXBsikMqJTDgo/SNPMjBGGcEnuAx6kTo8eKynbeJbe7YZXMn8m6CRb5RoPpaLxgxCiKe1QY58
  template:
    metadata:
      name: cloudflared-token
      namespace: cloudflared
    type: Opaque
