---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflared-token
  namespace: cloudflared
spec:
  encryptedData:
    token: AgAff3WAWPn598Co7UzN4yAovNpVdrL7jmi2JdEPh+bONbcIXGq2IlvZUpPc3YelITQ2GfmmEUGuhI1Mj9qa7FUumlcVGRUZOR+0TrEBT4coDEjZtds4dwshaEjzpSpBO4rUWFPWpl2OQ5QoDPZn/sAPsjHtgMye74hbdhR7xG8RyoBpUYSToJQUmfoDdI3wakfQiG/OIYdxsLZEfokmJMMz7ofHjAz1Y0TUOyRKo3xRS8tKu9U860pIWhKXbBe1EgU27etyDEAyAErvVV1uL6dRzkw79QPRXv1/qHgHqY2o4H4ZesWvTH9gkvJa0Pzpu/C5oEE/7UYnp1Yf+YVUYNV+nfFTbkRsboITm+VXVEOyICCajKrNXVA9JZJJFRYAQtCAnwyNGt3gB5e5PNgbVlNM1SpHE2P5Km7uGqCL8+ySEhbM9mCp7xBsQewfmk/Jz4v3e522JJgSp7JMTLpo/eII8BY3ui4XSVAv1nNEqgkKoQCHyz0PCCmZ/P/QM98ryjhEriIEGCtEm0Yxh/5fI2OWqNcZpCMXpo0ZyrSmTK5BkdwJpuvbw33z2GSUc5D63TGoWKLdHCNtmnAc+d+FN7V7FCILqcQVsFuI0Q0rsFEhNNRC4I3TJ80oT6UGEF3QEwh/OfZvpIRNP45PB0bcgFvUnVFZfw0iSTeddXhLtLbTfpcRbdnJ6v0wDCTTJO29u39FToBLx3507z9cXQIaGOCgcrE/dTEAGOIC+3Uzm84lwgQg98GYFjEXu0nYbgk87E6wJgHVPlqAocxbzibrAksBYx7VSvh/eM/zG1fxQX5yN7GAd4MexB9/WGQAtc3k3AN6joLls85cQfMCo832xMU3SpI/Z9J5Zi1vPgVpowc2YinVOxPK44N/MUhw8Rw4h36p0Il+EEpoWwTFF88uM0BoD3McwK10lXjUaG0QClecEevBvCt7xikR
  template:
    metadata:
      name: cloudflared-token
      namespace: cloudflared
    type: Opaque
