---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin-secret
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgCDWTDCXDscCUUFmKicJtlnAJloxh6Ydznya942+5oBnyuiWPohfmIV81UqNOZ5/yC0Mw/m+t+UpJdc2M7k+8Uh6WEvL4WIxP9Aolvhn/mcJUSGBev3z9+7bpR9IjKNBqTiwCSB9xYXTBTAlqCZuzhjCsVG/3/hmsy42S8v7tEs5CeTjLC8hfGdEWLvZWQhPFILpxBFQ4beJn8mBtBhAtdKUcv3zVVsi9l1iPk9nyZp8uObkpCTB9BXfilzODjLt6XuS/kgpXtJmYJpM1TC4yS8GMQBk41MdmOOKKHei8TFb+A7xaIExcFxyZn2Qss9BAb8kIX8QoQyljv3ODLEQfva+cUx6n8A1o15epPHIeix2ZZZPdrAitXf3AYhs9hrupa1gDJDFpdREXNC3OnL9K+9X07kK6N2iE3Nt6qHXKLXjx+Qz3wHCt6wEIdXPiLjahrLnlfOD5s5sk/Oq0IhHJ+45gn9NcvW+211U14CSi/DWdLCFukQgf9Ovh7swN8LWnupVANY3D3BuImlBymWrY7F1w7uvRkKeZmiKxpv/5SUNYk4/yD5dWqPV/uaesKluZBpDycxvWc9EKFT8yag46LJCke/TFUJhc31yDBLEw4hd/WXCBu4MasxIDNF6zOu1NPhiC9snHI+xoMrYSkhXk02l0bER1XqRd9Ddf18ASEPo7fm0esnRvduP/CLxEbthHKGtues9GzFLmkEgnmDVbfomQp2H9V1g1U=
    admin-user: AgB4TsL7yeTm9/Mv3Fuxd1M03b5U1cnI0oBuv0LdN57RVWd+YpQDiJjil5NpTNEznRSPYk/zNwXXS20QeM2xJ1Dno8OC+uiMxbMMHhiBvKSbEQK38RhwKpuBcECsgmbzLSPC133MrBZxFW/MGCscaNUs0NAK8BcveuVMxPpXW1BhozcccI4Lr3KpDSQbPIe1QKY6YTUBitdra9KSHCUFLxbKpM8w5hMpI74rOkSpl7vCSCqBPj71mtpfusWXlJ6agyfuyLFS2QgzfCX+O+/cHWi0K5tpKW/iP9sByoh7buv6wrU+nDD0v93jHrZenVnVPpcC2O/gAX08vWPa1AA9piggZPhaNd71Qc5KtbICspAAu89FsuUbo55IiWxLF1b7h4PyWm4CfwMIXXsaRwyEpj31D5KPDz+6p2p9VFK5jbB7ybj6Ukob6aEDvwjlDforRDe3eDAlRdjFBX7H/dHfsZZA5Co23lBgltzylsAab3Z02EPrK9YECz4H2SxzHwrpOAI5mO/mF3YmqRnHeDGZEB0vEPrCgRShMGYbmU7+tRbH/gsKk8QmWCUwAtzmWwtPHVYV9nb9R6k6mm3MG3Md7UJeD8l+s76Rrl8xO+O8xeGApPEA2QhgIsp9BQetCY24MemPjW/JBdVaSOwOJw6BRvJ2OG61OlEjm63/BsFlkY2mMlT3UEsGTbw895320sWLJU3vaqBCNg==
  template:
    metadata:
      name: grafana-admin-secret
      namespace: monitoring
    type: Opaque
