---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin-secret
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgAXy+44JrP4Atk6qAmK5WwpCa6IFaOm7IKZMPo5bqz4HbwlzgvEWuj6yTNJohizTy6ejwmgSI0wdLeaBkB9W9I3PjYSedsqmntuQWMbyK0VsRznmlyC8ey7bMaq08DX8SfDQhZYIcHTRWyHDVSzVkm3BOje1YRFCCHMxKd0qKZfPJODkmS4Sy13mRo0qt/7qv7+/qaXC+oiM6rYf7oyTTvo1pW9OafTVknWYGprmNj3xnmLzjBUkzVKlOBt6Qit+zRY+7f1GtngURqpdGYiIbRMZF3/WqtaX1IJkX1kQM0BdboUU88s9R5oixJJD4cg4TZE0ELctvjKKIucj9mYOTa23WdnzaOLsRi+J2+GIiZpTMXWwmrbNk1W3zTn8W1gHopWwABjW5ObPjKMmVCisw8UGJ2XZ5d5xxxkfIU534sUGftYmGawwCig++ta6KFCDvWRzRc80STKXt+VX+P+a6+bw4DChPe6KARlXQmMN3bo0D/pEv5BkxTGWybF2wRAeivC0CPE8UR6DUumbCbXyGdfJ+OzzwjUX5STcXslimegdBZ13C1wY/WREfMISXcM7kbaj+qPUBaolqNeHxrlNubFYqXnD2w5iI9IfZXaEPQAeWoNN6bkpPrK5bl3z+SQRvfvrx3B4NV5/z7RFt+qejuNfAqolDcQGZhBiZSLSYgV6lOuXZ53B589tV+T0UO7yqg5hsqFoMK0Qa2zNHoL+sxqe7g+W+4+3ss=
    admin-user: AgAzYE7lze9A/uTdwHe8uNWrORLzk2OxM/ARZI8Ttc3dSWyrLdr8BX/MTu9o/b2XfQjr/Zr/ElnwqohHVCQkeB3uJNT1A6psfeP3eUIpXpzTAvFura5ucfeEs4/SGFi3Bh+ZuonUF6K7lPxhEUgSxJjw+QFxfcILNV6llLhNaWpBW66TGx1Oitdego2E1d2E082wK0VqImoexZD07A8RekdXaNG1UwzFr+rNWoMY4458mn8enpbgH3BagqpEe2AZ7o9sR6WWvKDy0anQPJ8SSOlmhIT8CGQtWlMP2mIZSfXunRZ/luyGZROx44EXA1HU7PN1Ticf3bCUoB1B8yHigyRKGl+qEsPu+4zZdpO2HEu4Wmx/4PL56V6OXv8MEyGM85oPVkPEHK7hHWlP9Kj6eXpEbr3CtKWZ1rLl+Pf9PsAk2NKcMcNZn85IuMCULE4vz7PdB+aou44UTGU8HWTFrx2Car5vNvHGSl0t5YygwLCHuMQcQTMHpElcICLch1XOQnnbuU479GwokVw9iZ6KJCUJ4+RWuu0Ccs6YYJAQ+HAu64nLfImwo43iRagKCzOJQRl1TTyNlAgliPWAWeEVLMjgElz7/Jfzb6ymOeKllbQJRB/MuLgJznv/EX68hEvwDE0Ek5IilgJN4PlCi2FhpES1a5is3RQfjkL0ykBAK1tr7WwhqbnfaMQ2bQuwONe0hFrLWDUhpg==
  template:
    metadata:
      name: grafana-admin-secret
      namespace: monitoring
    type: Opaque
