---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin-secret
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgBQnocKd1soI0IegdtWzswiSuhSMmoBz1hfuo6gI97eOWZWHTHbDM2vNSKH6JOJ7AaSJ/dkG7oM9v50/mNeMMONgsiu18tWOQITjXRykCRwKB1/++CGEbjSb1Vy+mYCsMY1ZxYNr/UVTDrhdeSNHi9xM3zQoNScSEC4v9EJzzAgKl04CQGiwh2NFL664JWSESCymPeEWPRAlXRwlMsyUSCivTlUOsSC2/BUCrk8FyAKl/9gCr4ijzr1yGcQ1B1b6fQ+jDj138YpsooRMNrOITdAtRZpEaG0l0GBVj0H0RMcEPlTgp2J/s1Zj4RMq7cOTeIvBhYQ+jZ6SWPcHmi6C26tdvXJJLwaWkJvSKzWZz5UclhIS4vfCl3jkn5TTAh4MfzaZIK1kyAbW2KJMDekpj2uT96IaifdGS6T51jgeBmIUOAoi6kaDXsJc2vpq2XRtj1jTpVHx+rkwkcjXsIWyIAClThjJ75cYSBlfpecNFlC8UHt5xhcSbfqVmyOqjCqeCrRhkN6KIodQRPu/lVptXptXzgjeu81W8EcH/TlUgTpQ/Bq7MmdxKNQDWmkqAmQ+1QawO1XssMUF9JjEFPw2AeK+Ci4a/rK8pUTydpuCJS8xQy6ZG8pMmHoR5uolUxmvrWLwjfq12JfBdhvaKlV5jtmU9x3lHTvp9HoMN2V4M3Eyp1bMB/wz3hlNqbpVSlyNJvqVoEMy9UKRR0+3jU9jA0o5H0PcoGo8L0=
    admin-user: AgCOHegbfcXdZfe4ceLjqZwDZt1F8UUKGiFTI5vckdVNmeCg3a+Q2KYpVK0GTTJRvBALbmfipJ9f5ajqQqjH8AV1N5qNhnUSVGKKtt/etisvP2DYxopF9WU/mIKlHLFprkk2XcXfIBochBsSRB81pMy4zOnKoBGBANMSoUz+CAoaZxoZNiHpFGTonaXEUFaPXHccQfhl8U5LS+zfEyTvJM4jM8c4jLRNoIrI5+exaoq3mJagPwLoRSkqrq/7iBWc4BMdqjvE/buqs/z7WUFzmK5hYakA1zJRAopQC6upsY0/3231sOS4gF1x+ErkqpaIVPwL904y/Hf5VyOHWQtEKE6U2+F4rOF0XNP9n9KXBATtz4gSKbAkFKJu0HZtOUre3ytyVQpzN38J32D8m73ftxFWmF6B3c0EXBl4wUAq15cH96jf+jl2S0iwGytVK/P0UGtMkMBxqAGD0R6HD5cO22ghFIGlZODun73UIySL6IME4tTJkIJAKLBNs4wL2WfX9+j0mQ0aV42YYyN4JPyZ+greWCa2Zbhfd9DPcFghd26EuvaagIAy1YMSzHnDFlSQQ7pKGjhUqLeftD3P8V6doQTBu2v8Mvry6L+/4sbc5jNX0IvFrefSUOyeZWMQ0AFC48MlcFHHWo6YafhQNIfqBEqqj9ieQzbS1c2W9S2WV4ArJT92Pcy/OSqh3k9+RaJilAVLL/jnpA==
  template:
    metadata:
      name: grafana-admin-secret
      namespace: monitoring
    type: Opaque
