apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cloudflared-token.yaml
  - authentik-secrets.yaml
  - n8n-encryption-key.yaml
  - actualtap-secrets.yaml
  - paperless-secrets.yaml
  - paperless-raw-backup-secret.yaml
  - actualbudget-raw-backup-secret.yaml