---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: n8n-encryption-key
  namespace: n8n
spec:
  encryptedData:
    N8N_ENCRYPTION_KEY: AgBBzgJmlZfsAcMRPIiPPen/G42BFXIGRHs1xc65tN3hUXct7gN4sovmjxFP/wrzsW/Y7aSPi6Mn6V9/FLQSqNVhrjbb9d7LxEpAJsmVaL0VycLMTb3a0s0eYlisDhOiM07EsE1l0Z4munj72wML+MBC7SLChwqMT975edGYxz0ZUreQsR68qwNIuYxAVkAlYnoMAsM4FmLddtlyNW2Il/XJ/mw7RZGKothzzstCt5gSMJ/UsDgPuUKlngdnSN2xcIIPjLEAN4Jgb5dSNOTnL5Qv7V+XSOHRq+EyMpXLi4M7W81fb9sj6x4hs3okuMEzN0dDMsbQHYfaS1Q7EKfEvk/0PIxsdBbxZsBV3seB2vBSeYeGz6N4bJZnC0eQXn5mG+/DZtRpLDabpBccvK16/xCvOJKBNwx96Hb8xDjJ3etXrHrZMBhraEpq4EQDFk988WNnFRucy40OvdKwzAqd6ZztvY76kg97LKVnrxs+koDLZ62Dnlb2/q/Fo+qyHIHSbGg7O0ju8vWlqk5gwDsNV3EXRWRCsXumZETCM0xmyEhYT2VwTjBOXjUtIALzSy7kkkkKEs7KczJfO/XgtPjZNrfSljX/Emu+U0tQLH3OOMJ2moPkV4UJ4TLjSEfdL+VLuy+HRIWQowxWX7Yuim2Q01hNW1rHgmoxSFOlRVCLDPWZHki/7/c277o6nSKCyx0mm1SSX/Q5/ZASQZRGMJWwAo4ox911U8BP64H24/VWmvgE6g==
  template:
    metadata:
      name: n8n-encryption-key
      namespace: n8n
    type: Opaque
