---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: n8n-encryption-key
  namespace: n8n
spec:
  encryptedData:
    N8N_ENCRYPTION_KEY: AgBfiunhwOpxEPUm9oWBgVVHfiKJ8WqTfMUKmgoOtEbdOH+W14dV43mtqF/Jed2xgTKZF+3dlwUs8bkeE4MYktxkZfz61xVeUNO3GdJMri+0loDJRc0XNPP0NUN9oCVxAb04G3c0RREgdMgWoysyLF+xDgg5PlvGlbGUULTxOWyNj33LlFNQp6oBI5Sr152DDRI93ZOmqRgOoLabacanxLooC6exQdtVvoigohTUAdyjbBeesqbiF2IDzO+GKNQYjmx64J1RfYUfW5mD9dWWRCeSuF66LvlyzMfje4SaOBOiM5wVlQ4rpd/Okmv1p9RHpcqXqxuAg7WFT9053ux+o9aflU7G4VDe0vaOv5zzf/SSDqBeA3mRduqR05D+Sup3pgqqdPVDJKGXSSzMddE0YWv/wZ7V+8f5UevO+z3nLqVCxZppoxWrJVjTWICEo8kW0gvKfBvNWyDjmDLxjA8OoYLZY0HfSV9cqn+Q7GlSNXDdayCa2AzpqTCHvZ+Jo+uIhQ6FCR2VsJae59xGcIGTesEAreG4c7SBQ00+/BtyYS0Un6nykvKH4GZF3amq3/2ob1s1XuL+ogg9G4Ft3dMXGtMOImV4Rx7p+80qRgmdwcLmXt3CxT5yNOiLGa2MRMZGZcmLk94+zqzjHdLAg6hom70lqF5qC2wqKyj1X7WMfJOoKnpZ+SmbqBP3t8CJICBvRKN6ZTcTBzr24ksei7I9fDJKMyvaNfzyt03t6rn70EZOjQ==
  template:
    metadata:
      name: n8n-encryption-key
      namespace: n8n
    type: Opaque
