---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: n8n-encryption-key
  namespace: n8n
spec:
  encryptedData:
    N8N_ENCRYPTION_KEY: AgCByPm2aLhqjcdcsvcOYXk4X0rLoHcSGgL87j2VrM5EFqyK3KS8LRICGlYIupm7DesS8KstIe2clGeldtiCi+fnIUSKDeRvA2aEk+Fo3hkvYW8P7ltzzDyTBQLfBREk6Qv/U1WqbKnHNiLJVzxDD3PqK6sE9BaxJeOm7lLj7nkJt0gWFtNyqrkqpiZ32DDz1/ss9TeFPNlnZO1YBTTEkAzDrSn29BVCtz9HOv+rXoI7PkPnmLHyu0I75b2HWcG7kTxQfWzcunBNBRu7hvqcTBTEwV8AmlKOQ/VZo95dOrorbwxKyJyIGo3Ga4AenmzrxH7R5ZGTKFBHPvZLBiFwEH7CN6OgJpVk/Vl/AFSPmDmmLdhaic3x6Mf9YGGYEGjSD1p/LkgyZbixJV63jChg2dX16uESZkSB3MY5OxjQY4VkpbJs/OUc81hG04EoIWRxsVJYbpzIlHYsuIjlc0vdX1Fn7IPAnQMpG18NT98FjA1rjvQYkc4Fej0YaxCD8SIt36OIsigmFT1xVEJ+oxEmSxa+avqGM1K7vrzgAhCZ2BDkTia56oGUj0zmMIIAnMYRsqQ+ep+WJthvFxlAsgl7IXD6f2cwhK1BF1+ATYWG2E6V1ydtQr6YOWffprFV91tM/xdPF5ebp5waaZLtTkvIJGevm3E+MhnG77irFMT2e79Rfsw4FId/pARiYjQQuguUS7/cGjpAMPHxGnvrG632i3syiIXhwrIbz1BGex/1sTM7AA==
  template:
    metadata:
      name: n8n-encryption-key
      namespace: n8n
    type: Opaque
