apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: n8n
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://community-charts.github.io/helm-charts
    chart: n8n
    targetRevision: 1.16.33
    helm:
      values: |
        timezone: "Europe/Zurich"

        existingEncryptionKeySecret: "n8n-encryption-key"

        extraEnvVars:
          N8N_LISTEN_ADDRESS: "0.0.0.0"
          N8N_PROTOCOL: "https"
          N8N_SECURE_COOKIE: "true"
          WEBHOOK_URL: "https://n8n.b164.dev/"

        main:
          persistence:
            enabled: true
            size: 2Gi

        ingress:
          enabled: true
          className: traefik
          annotations:
            traefik.ingress.kubernetes.io/router.entrypoints: websecure
            traefik.ingress.kubernetes.io/router.tls: "true"
            cert-manager.io/cluster-issuer: letsencrypt-cloudflare
          hosts:
            - host: n8n.b164.dev
              paths:
                - path: /
                  pathType: Prefix
          tls:
            - hosts:
                - n8n.b164.dev
              secretName: n8n-b164-dev-tls
  destination:
    server: https://kubernetes.default.svc
    namespace: n8n
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
