apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pihole
  namespace: pihole
spec:
  interval: 5m
  chart:
    spec:
      chart: pihole
      version: 2.x.x
      sourceRef:
        kind: HelmRepository
        name: mojo2600
        namespace: flux-system
  install:
    createNamespace: false
  values:
    TZ: "Europe/Zurich"
    DNS1: "1.1.1.1"
    DNS2: "9.9.9.9"
    existingSecret: "pihole-secret"

    # Persistence
    persistentVolumeClaim:
      enabled: true
      size: 1Gi
      accessModes: [ReadWriteOnce]

    # --- Networking ---
    # Expose ONLY DNS via ServiceLB (outside the cluster)
    serviceDns:
      type: LoadBalancer
      externalTrafficPolicy: Local

    # Keep the Web UI internal (ClusterIP) to avoid port 80 conflict with Traefik
    serviceWeb:
      type: ClusterIP
      http:
        enabled: true
        port: 8080          # <- internal service port (any free port is fine)
      https:
        enabled: false

    # Route the Web UI through Traefik on port 80/443 via Ingress
    ingress:
      enabled: true
      className: traefik
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: web
      hosts:
        - host: pihole.local.lan
          paths:
            - path: /
              pathType: Prefix
      tls: []               # add a secret here later if you want HTTPS

    # Resources (unchanged)
    resources:
      requests:
        cpu: 50m
        memory: 256Mi
      limits:
        cpu: 300m
        memory: 512Mi
