apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pihole
  namespace: pihole
spec:
  interval: 5m
  chart:
    spec:
      chart: pihole
      version: 2.34.0
      sourceRef:
        kind: HelmRepository
        name: mojo2600
        namespace: flux-system
  install:
    createNamespace: false
  values:
    TZ: "Europe/Zurich"
    DNS1: "1.1.1.1"
    DNS2: "9.9.9.9"
    existingSecret: "pihole-secret"

    # Persistence
    persistentVolumeClaim:
      enabled: true
      size: 1Gi
      accessModes: [ReadWriteOnce]

    # These get written into pihole.toml -> custom.list, but Pi-hole overwrites on restart.
    # We'll keep them for pihole/pihole.homepage, but rely on dnsmasq.d for test + future
    customDnsEntries:
      - "192.168.1.49 homepage.local.lan"
      - "192.168.1.49 pihole.local.lan"
      - "192.168.1.49 test.local.lan"

    # Mount our own dnsmasq.d snippet so changes are always picked up
    extraVolumes:
      - name: custom-dnsmasq
        configMap:
          name: pihole-custom-dnsmasq

    extraVolumeMounts:
      - name: custom-dnsmasq
        mountPath: /etc/dnsmasq.d/02-custom.conf
        subPath: 02-custom.conf

    # Force a rollout when config changes
    podAnnotations:
      redeploy-timestamp: "2025-10-09T20:55:00Z"

    # --- Networking ---
    serviceDns:
      type: LoadBalancer
      externalTrafficPolicy: Local

    serviceWeb:
      type: ClusterIP
      http:
        enabled: true
        port: 8080
      https:
        enabled: false

    ingress:
      enabled: true
      ingressClassName: traefik
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: web
      hosts:
        - pihole.local.lan
      path: /
      pathType: Prefix
      tls: []

    resources:
      requests:
        cpu: 50m
        memory: 256Mi
      limits:
        cpu: 300m
        memory: 512Mi
