apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pihole
  namespace: pihole
spec:
  interval: 5m
  chart:
    spec:
      chart: pihole
      version: 2.34.0
      sourceRef:
        kind: HelmRepository
        name: mojo2600
        namespace: flux-system
  install:
    createNamespace: false
  values:
    TZ: "Europe/Zurich"
    DNS1: "1.1.1.1"
    DNS2: "9.9.9.9"
    existingSecret: "pihole-secret"

    # Persistence
    persistentVolumeClaim:
      enabled: true
      size: 1Gi
      accessModes: [ReadWriteOnce]
    
    customDnsEntries:
      - "192.168.1.49 homepage.local.lan"
      - "192.168.1.49 pihole.local.lan"
      - "192.168.1.49 test.local.lan"


    # --- Networking ---
    # Expose ONLY DNS via ServiceLB (outside the cluster)
    serviceDns:
      type: LoadBalancer
      externalTrafficPolicy: Local

    # Web UI inside cluster; Traefik will route to it
    serviceWeb:
      type: ClusterIP
      http:
        enabled: true
        port: 8080
      https:
        enabled: false

    # Ingress schema expected by the chart (hosts as strings)
    ingress:
      enabled: true
      ingressClassName: traefik
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: web
      hosts:
        - pihole.local.lan
      path: /
      pathType: Prefix
      tls: []  # add a secret here later if you want HTTPS

    # Resources (unchanged)
    resources:
      requests:
        cpu: 50m
        memory: 256Mi
      limits:
        cpu: 300m
        memory: 512Mi