---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: capacitor
  namespace: flux-system
spec:
  interval: 12h
  url: oci://ghcr.io/gimlet-io/capacitor-manifests
  ref:
    semver: ">=0.1.0"
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: capacitor
  namespace: flux-system
spec:
  targetNamespace: flux-system
  interval: 1h
  retryInterval: 2m
  timeout: 5m
  wait: true
  prune: true
  path: "./"
  sourceRef:
    kind: OCIRepository
    name: capacitor
---
apiVersion: v1
kind: Service
metadata:
  name: capacitor-direct
  namespace: flux-system
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/instance: capacitor
    app.kubernetes.io/name: onechart
  ports:
    - name: http
      port: 9000
      targetPort: 9000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: capacitor
  namespace: flux-system
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web   # or websecure + tls if HTTPS-only
spec:
  ingressClassName: traefik
  rules:
    - host: capacitor.local.lan
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: capacitor-direct
                port:
                  number: 9000
