replicaCount: 0

image:
  repository: ghcr.io/paperless-ngx/paperless-ngx
  tag: "latest"
  pullPolicy: IfNotPresent

redis:
  image:
    repository: redis
    tag: "7-alpine"
    pullPolicy: IfNotPresent
  port: 6379

nameOverride: ""
fullnameOverride: ""

existingSecret: paperless-secrets

env:
  PAPERLESS_URL: "https://paperless.local.lan"
  PAPERLESS_CSRF_TRUSTED_ORIGINS: "https://paperless.local.lan"
  PAPERLESS_TIME_ZONE: "Europe/Zurich"
  PAPERLESS_OCR_LANGUAGE: "deu+eng"
  PAPERLESS_OCR_LANGUAGES: "deu"
  PAPERLESS_WEBSERVER_WORKERS: "2"
  PAPERLESS_TASK_WORKERS: "2"
  PAPERLESS_THREADS_PER_WORKER: "1"

service:
  type: ClusterIP
  port: 8000
  targetPort: 8000

ingress:
  enabled: true
  className: "traefik"
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
  hosts:
    - host: paperless.local.lan
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - paperless.local.lan

persistence:
  storageClass: "longhorn-replicated"
  accessMode: ReadWriteOnce
  data:
    size: 1Gi
    volumeName: pvc-cfd22e58-13bb-4827-918d-14ea3f4648f4
  media:
    size: 20Gi
    volumeName: pvc-a560d5ec-fe3e-4a5a-a0a2-03a4e71cf60c
  export:
    size: 2Gi
    volumeName: pvc-175038b1-1ff0-4f77-bbc8-8c80472baa88
  consume:
    size: 1Gi
    volumeName: pvc-0f3f8b4b-7465-4fc6-8d66-3f9420073321

resources:
  limits:
    cpu: "2"
    memory: 2Gi
  requests:
    cpu: 500m
    memory: 1Gi

redisResources:
  limits:
    cpu: 200m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 32Mi
