apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "paperless-ngx.fullname" . }}-redis
  labels:
    {{- include "paperless-ngx.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "paperless-ngx.redisSelectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "paperless-ngx.redisSelectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: redis
          image: "{{ .Values.redis.image.repository }}:{{ .Values.redis.image.tag }}"
          imagePullPolicy: {{ .Values.redis.image.pullPolicy }}
          ports:
            - name: redis
              containerPort: {{ .Values.redis.port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.redisResources | nindent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "paperless-ngx.fullname" . }}-redis
  labels:
    {{- include "paperless-ngx.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.redis.port }}
      targetPort: {{ .Values.redis.port }}
      protocol: TCP
      name: redis
  selector:
    {{- include "paperless-ngx.redisSelectorLabels" . | nindent 4 }}
