apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: homepage
  namespace: homepage
spec:
  interval: 5m
  chart:
    spec:
      chart: ./clusters/home-cluster/apps/homepage
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
