apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: homepage
  namespace: homepage
spec:
  interval: 5m
  chart:
    spec:
      # Path to your chart, relative to the GitRepository root that Flux bootstrapped
      chart: ./clusters/home-cluster/apps/homepage
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  # Optional: override values.yaml here if you want
  # values:
  #   service:
  #     type: ClusterIP
  #     port: 3000
