image:
  repository: ghcr.io/gethomepage/homepage
  tag: v0.9.12
  pullPolicy: IfNotPresent

fullnameOverride: homepage
replicaCount: 1

service:
  type: ClusterIP
  port: 3000

ingress:
  enabled: true
  className: traefik
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    cert-manager.io/cluster-issuer: letsencrypt-cloudflare
  hosts:
    - host: homepage.b164.dev
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - homepage.b164.dev
      secretName: homepage-b164-dev-tls

resources: {}

env: {}

nodeSelector: {}
tolerations: []
affinity: {}

rbac:
  create: false
serviceAccount:
  create: false
  name: homepage

config:
  mountPath: /app/config
  files:
    kubernetes.yaml: |
      kubernetes:
        mode: cluster
        # optional:
        # refreshSeconds: 15
        
    settings.yaml: |
      title: "My Homelab"
      theme: dark
      headerStyle: clean

    widgets.yaml: |
      - openmeteo:
          label: Winterthur
          latitude: 47.5024
          longitude: 8.7241
          timezone: Europe/Zurich
          units: metric
          cache: 5
          format:
            maximumFractionDigits: 1

    services.yaml: |
      - Cluster:
          - "k3s Dashboard":
              href: https://k3s.b164.dev/
              description: UI for k3s
              icon: kubernetes
          - "ArgoCD":
              href: http://argo.local.lan/
              description: UI ArgoCD
              icon: argo-cd
          - "Longhorn":
              href: https://longhorn.b164.dev/
              description: Distributed Storage
              icon: longhorn
          - "Grafana":
              href: https://grafana.b164.dev/
              description: Monitoring & Dashboards
              icon: grafana
      - Automation:
          - "n8n":
              href: https://n8n.b164.dev/
              description: Workflow Automation
              icon: n8n
      - Finance:
          - "Actual Budget":
              href: https://budget.b164.dev/
              description: Personal Budgeting
              icon: actual-budget
      - Documents:
          - "Paperless-ngx":
              href: https://paperless.b164.dev/
              description: Document Management
              icon: paperless-ngx
      - Security:
          - "Authentik":
              href: https://auth.b164.dev/
              description: SSO Identity Provider
              icon: authentik
      - Networking:
          - "AdGuard Home":
              href: http://adguard.local.lan/
              description: DNS Blocker
              icon: adguard-home
          - "Unifi Controller":
              href: https://unifi.local.lan:8443
              description: Network Management
              icon: unifi
          - "Zyxel Router":
              href: http://zyxel.local.lan
              description: ISP Router
              icon: router
