replicaCount: 1

image:
  repository: ghcr.io/mattfaz/actualtap
  tag: "latest"
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 3001
  targetPort: 3001

ingress:
  enabled: true
  className: "traefik"
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    cert-manager.io/cluster-issuer: letsencrypt-cloudflare
  hosts:
    - host: actualtap.b164.dev
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - actualtap.b164.dev
      secretName: actualtap-b164-dev-tls

envFrom:
  - secretRef:
      name: actualtap-secrets

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi
