apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rcw-portal
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/lukasweibel/homelab.git
    targetRevision: main
    path: clusters/home-cluster/apps/rcw-portal
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: rcw-portal
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
