replicaCount: 2

image:
  repository: cloudflare/cloudflared
  tag: "latest"
  pullPolicy: Always

tunnel:
  secretName: cloudflared-token
  secretKey: token

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi
