apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://traefik.github.io/charts
    chart: traefik
    targetRevision: 29.0.0
    helm:
      values: |
        ingressClass:
          enabled: true
          isDefaultClass: false
          name: traefik
        service:
          type: LoadBalancer
          spec:
            externalTrafficPolicy: Local
        ports:
          web:
            port: 80
            expose:
              default: true
            exposedPort: 80
            protocol: TCP
          websecure:
            port: 443
            expose:
              default: true
            exposedPort: 443
            protocol: TCP
        providers:
          kubernetesCRD:
            enabled: true
          kubernetesIngress:
            publishedService:
              enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: traefik
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true