apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: actualbudget-raw-backup
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/lukasweibel/homelab.git
    targetRevision: main
    path: clusters/home-cluster/apps/actualbudget-raw-backup
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: actual-budget
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
