apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "freshrss.fullname" . }}
  labels:
    {{- include "freshrss.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "freshrss.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "freshrss.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          env:
            {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
            - name: FRESHRSS_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.existingSecret }}
                  key: FRESHRSS_USER
          startupProbe:
            httpGet:
              path: /
              port: {{ .Values.service.targetPort }}
            failureThreshold: 60
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.service.targetPort }}
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.service.targetPort }}
            periodSeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- if .Values.persistence.enabled }}
          volumeMounts:
            - name: data
              mountPath: /var/www/FreshRSS/data
          {{- end }}
      {{- if .Values.persistence.enabled }}
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "freshrss.fullname" . }}-data
      {{- end }}
