apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  source:
    repoURL: https://github.com/lukasweibel/homelab.git
    targetRevision: main
    path: clusters/home-cluster/argocd/apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
