apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "homepage.fullname" . }}-config
  labels:
    {{- include "homepage.labels" . | nindent 4 }}
data:
{{- range $filename, $content := .Values.config.files }}
  {{ $filename }}: |
{{ tpl $content $ | indent 4 }}
{{- end }}
