ingress:
  enabled: true
  className: traefik
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
    traefik.ingress.kubernetes.io/router.middlewares: default-redirect-to-https@kubernetescrd
  hosts:
    - host: homepage.local.lan
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: homepage
              port:
                number: 3000
  tls:
    - secretName: homepage-tls
      hosts:
        - homepage.local.lan
